### ISSUE TITLE
Odd graphical behaviour when dragging window

### ISSUE THREAD

**Issue by ohlookitsderpy** [LISTEN-moe/desktop-app#16] opened 2019-11-10 12:04 UTC
When moving the window around, I get these black boxes in random places: <img src='https://u.derpyenterprises.org/ZVlR'> <img src='https://u.derpyenterprises.org/hbrR'> This issue appears to be overcome by dragging at the bottom of the window, and doesn't appear afterwards. I am unsure whether this is related to being on a copy of Insiders or not.

System Information:
LISTEN Version: latest
OS Version: Windows 10 Home 1909
Screen Resolution 2560x1440

**Comment by kotsh** [comment] 2020-04-03 01:17
It seems to be a little more transparent for me, but its there. I'm not on Insiders and I'm on the latest version as well.
Screen resolution is 1920x1080

**Comment by kotsh** [comment] 2020-04-03 01:19
This also seems to happen only when gaps are on in settings.

**Comment by robflop** [comment] 2020-07-25 10:17
This seems to be fixed as of commit b09f4da3479fa5678986946fd2291b2a9fc62c77. Behavior as described above is not happening in a build of commit 388a933cb928120a46e83c63d9fc587466432f08 anymore, so I'm thinking b09f4da3479fa5678986946fd2291b2a9fc62c77 fixed it.

**Comment by ohlookitsderpy** [comment] 2020-08-06 17:12
I can no longer reproduce this issue as of latest build (0.3.0).

If it's fixed for @kotx as well, then I think it's safe to close the issue now.

**Closed** 2020-08-06 17:22 UTC

**Comment by kotx** [comment] 2020-08-06 17:40
I can't reproduce it either so presumably its fixed.
